- name: catalogue configuration
  hosts: catalogue
  become: yes
  tasks:
    - name: disable old nodejs and enable nodejs version 18
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present